In [1]:
!Github URL = https://github.com/Yjongbeom/OpensourceSW-Programming.git

/bin/bash: line 1: Github: command not found


# 예제 1

In [2]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


# 예제 2

In [4]:
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]


# 예제 3

In [5]:
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


# 예제 4

In [6]:
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


# 예제 5

In [7]:
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f'Map function:\n>> {map(ord, symbols)}')
print(f'List after map:\n>> {list(map(ord, symbols))}')

[126] 

Map function:
>> <map object at 0x7cceac11b910>
List after map:
>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


# 예제 6

In [8]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


# 예제 7

In [9]:
import array

symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

(33, 35, 94, 38, 38, 35)
array('I', [33, 35, 94, 38, 38, 35])


# 예제 8

In [10]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
    print(tshirt)

black S
white S
black M
white M
black L
white L


# 예제 9

In [13]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


# 예제 10

In [14]:
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


# 예제 11

In [15]:
lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


# 예제 12

In [16]:
a=10; b=20
b, a = a, b
print(a, b)

20 10


# 예제 13

In [20]:
print(divmod(20, 8))

t = (20, 8)
print(divmod(*t))

quotient, remainder = divmod(*t)
print((quotient, remainder))

(2, 4)
(2, 4)
(2, 4)


# 예제 14

In [21]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrea.pub')
filename

'idrea.pub'

# 예제 15

In [23]:
a, b, *rest = range(5)
print((a, b, rest))

a, b, *rest = range(3)
print((a, b, rest))

a, b, *rest = range(2)
print((a, b, rest))

(0, 1, [2, 3, 4])
(0, 1, [2])
(0, 1, [])


# 예제 16

In [24]:
a, *body, c, d = range(5)
print((a, body, c, d))

*head, b, c, d = range(5)
print((head, b, c, d))

(0, [1, 2], 3, 4)
([0, 1], 2, 3, 4)


# 예제 17

In [26]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28.613889, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


# 예제 18

In [29]:
from collections import namedtuple

City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
print(tokyo)

print(tokyo.population)
print(tokyo.coordinates)
print(tokyo[1])

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


# 예제 19

In [31]:
print(City._fields)

LatLong = namedtuple('LatLong', 'lat long')
delhi_data = {'Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208)}

delhi = City._make(delhi_data)
print(delhi._asdict())

for key, value in delhi._asdict().items():
    print(key + ':', value)

('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': LatLong(lat=28.613, long=77.208), 'population': 'IN', 'coordinates': 21.935}
name: Delhi NCR
country: LatLong(lat=28.613, long=77.208)
population: IN
coordinates: 21.935


# 예제 20

In [32]:
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])

[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


# 예제 21

In [33]:
invoice = """
0.....6..................25.......33......40.......
1909  Pimoroni PiBrella     $17.50   3    $52.50
1489  6mm Tactile           $4.95    2    $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni PiBrella  
   $4.95 6mm Tactile        
 


# 예제 22

In [34]:
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


# 예제 23

In [35]:
l[2:5] = 100

TypeError: can only assign an iterable

# 예제 24

In [36]:
l[2:5] = [100]
print(l)

[0, 1, 100, 22, 9]


# 예제 25

In [37]:
l = [1, 2, 3]
print(l * 5)

5 * 'abcd'

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


'abcdabcdabcdabcdabcd'

# 예제 26

In [38]:
board = [['_'] * 3 for i in range(3)]
print(board)

board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


# 예제 27

In [39]:
weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board[1][2] = '0'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]


# 예제 28

In [40]:
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

# 예제 29

In [41]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

# 예제 30

In [42]:
l = [1, 2, 3]
print(id(l))

l *= 2
print(l)

print(id(l))

137227367609536
[1, 2, 3, 1, 2, 3]
137227367609536


# 예제 31

In [43]:
t = (1, 2, 3)
print(id(t))

t *= 2
print(id(t))

137226534309120
137227146435680


# 예제 32

In [46]:
t = (1, 2, [30, 40])

print(t)

t[2] += [50, 60]

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는
    메시지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

"답은 d"

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

# 예제 33

In [45]:
print(t)

(1, 2, [30, 40, 50, 60])


# 예제 34

In [47]:
fruits = ['grape', 'rasberry', 'apple', 'banana']
print(sorted(fruits))

print(fruits)

print(sorted(fruits, reverse=True))

print(sorted(fruits, key=len))

['apple', 'banana', 'grape', 'rasberry']
['grape', 'rasberry', 'apple', 'banana']
['rasberry', 'grape', 'banana', 'apple']
['grape', 'apple', 'banana', 'rasberry']


# 예제 35

In [48]:
print(sorted(fruits, key=len, reverse=True))

print(fruits)

fruits.sort()
print(fruits)

['rasberry', 'banana', 'grape', 'apple']
['grape', 'rasberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'rasberry']


# 예제 36

In [49]:
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.3064117553161294

# 예제 37

In [50]:
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')

with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

print(floats2[-1])

floats == floats2

0.3064117553161294


True

# 예제 38

In [51]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))

print(memv[0])

memv_oct = memv.cast('B')
print(memv_oct.tolist())

memv_oct[5] = 4
print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 1024, 1, 2])


# 예제 39

In [52]:
import numpy
a = numpy.arange(12)
print(a)

print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


# 예제 40

In [53]:
print(a.shape)

a.shape = 3,4
print(a)

(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 예제 41

In [54]:
print(a[2])

print(a[2, 1])

print(a[:, 1])

[ 8  9 10 11]
9
[1 5 9]


# 예제 42

In [55]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# 예제 43

In [56]:
from collections import deque

dq = deque(range(10), maxlen=10)
print(dq)

dq.rotate(3)
print(dq)

dq.rotate(-4)
print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)


# 예제 44

In [57]:
dq.appendleft(-1)
print(dq)

dq.extend([11, 22, 33])
print(dq)

dq.extendleft([10, 20, 30, 40])
print(dq)

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)
